### ISSUE TITLE
Registrations edit page is broken for previously delegated competitions

### ISSUE THREAD

**Issue by viroulep** [cubing/worldcubeassociation.org#473]
I used to go to these pages to check on email addresses for people claiming wca id.
I didn't investigate why, but right now it seems broken (I tried accessing [this competition](https://www.worldcubeassociation.org/competitions/ChamberyCube2015/edit/registrations), it also breaks for all the other I tested) : I get the "We're sorry, but something went wrong" error.

It definitely worked like one/two weeks ago, so I believe this is a regression.

**Comment by jfly** [comment]
Good catch! Investigating now...

**Comment by jfly** [comment]
```
I, [2016-04-06T16:35:53.524977 #16534]  INFO -- : Completed 500 Internal Server Error in 41ms (ActiveRecord: 1.9ms)
I, [2016-04-06T16:35:53.525280 #16534]  INFO -- : [User Id] Request was made by user id: 8
F, [2016-04-06T16:35:53.531813 #16534] FATAL -- : 
ActionView::Template::Error (undefined method `to_date' for nil:NilClass):
    1: <div class="container-fluid">
    2:   <div class="row">
    3:     <div id="competition-nav">
    4:       <% nav_items = [
    5:           {
  app/views/registrations/edit_registrations.html.erb:62:in `block (5 levels) in _app_views_registrations_edit_registrations_html_erb__3941253553078415316_69853717419080'
  app/views/registrations/edit_registrations.html.erb:44:in `block (4 levels) in _app_views_registrations_edit_registrations_html_erb__3941253553078415316_69853717419080'
  app/helpers/application_helper.rb:95:in `call'
  app/helpers/application_helper.rb:95:in `block (2 levels) in wca_table'
  app/helpers/application_helper.rb:94:in `block in wca_table'
  app/helpers/application_helper.rb:93:in `wca_table'
  app/views/registrations/edit_registrations.html.erb:13:in `block (3 levels) in _app_views_registrations_edit_registrations_html_erb__3941253553078415316_69853717419080'
  app/views/registrations/edit_registrations.html.erb:6:in `each'
  app/views/registrations/edit_registrations.html.erb:6:in `block (2 levels) in _app_views_registrations_edit_registrations_html_erb__3941253553078415316_69853717419080'
  app/views/registrations/edit_registrations.html.erb:5:in `block in _app_views_registrations_edit_registrations_html_erb__3941253553078415316_69853717419080'
  app/views/registrations/_nav.html.erb:2:in `block in _app_views_registrations__nav_html_erb__3792384320043063493_24591040'
  app/views/competitions/_nav.html.erb:127:in `_app_views_competitions__nav_html_erb___738424111363097408_21648280'
  app/views/registrations/_nav.html.erb:1:in `_app_views_registrations__nav_html_erb__3792384320043063493_24591040'
  app/views/registrations/edit_registrations.html.erb:3:in `_app_views_registrations_edit_registrations_html_erb__3941253553078415316_69853717419080'
  app/controllers/registrations_controller.rb:30:in `edit_registrations'
  lib/middlewares/warden_user_logger.rb:11:in `call'
  lib/middlewares/fix_accept_header.rb:12:in `call'
```

So the problem is due to registrations with a NULL `created_at` field. The `created_at` was only introduced here https://github.com/jfly/worldcubeassociation.org/blob/f3460fffee2601dec50006d9d1f378c2efe4415c/WcaOnRails/db/migrate/20151222013017_add_timestamps_to_preregs.rb, and it is allowed to be NULL.

@jonatanklosko, could you look into this? It would be pretty straightforward to add an if statement to the view, but I'd also be open to a migration that makes this field NOT NULL, and fills in some date for all our existing Preregs without a `created_at` field.
